version: '2'
services:
  web:
      image: hitalos/laravel:latest
      ports:
          - 3000:80
          - 3001:8000
      volumes:
          - ./:/var/www
      links:
          - db
      environment:
          DB_HOST: db
          DB_DATABASE: forge
          DB_USERNAME: forge
          DB_PASSWORD: secret
          DB_CONNECTION: mysql
  db:
      image: mysql
      environment:
          # with mysql
          MYSQL_DATABASE: forge
          MYSQL_USER: forge
          MYSQL_PASSWORD: secret
          MYSQL_ROOT_PASSWORD: groot
